FROM postgres:16.2-bookworm

# Install ssh
RUN apt-get update && apt-get install -y openssh-server
RUN mkdir -p /var/run/sshd
RUN echo 'root:password' | chpasswd
RUN sed -i 's/#PermitRootLogin prohibit-password/PermitRootLogin yes/' /etc/ssh/sshd_config
EXPOSE 22

# Deploy public key for ssh
COPY ./pg-test.pub /root/pg-test.pub
RUN mkdir -p /root/.ssh
RUN cat /root/pg-test.pub > /root/.ssh/authorized_keys
RUN chmod 600 -R /root/.ssh
